---
name: replace tokens
description: A GitHub action to replace tokens in a file.
author: Jon LaBelle
branding:
  icon: percent
  color: purple
inputs:
  path:
    description: |
      Replacement file path(s).
      Specifies a path to one or more locations.
      Wildcards are accepted.
      The default location is the current directory (`.`).
      Search multiple paths by separating with a comma.
      Example: `./path/to/my/settings.json`
    required: true
  filter:
    description: |
      Filter to qualify the `path` parameter.
      Only supports `*` and `?` wildcards.
      Example: `*.json`
    required: false
  recurse:
    description: |
      Whether or not to recurse directories.
      The default is `false`, or no directory recursion.
    required: false
    default: 'false'
  depth:
    description: |
      Depth of directory recursion.
      Only valid if the `recurse` option is enabled.
      There default depth is not set.
    required: false
    default: '0'
  follow-symlinks:
    description: |
      Whether or not to follow symbolic links.
      The default behavior is not to follow symbolic links.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: replace tokens
      shell: pwsh
      run: |
        $params = @{
          Path = "${{ inputs.path }}" -split ',\s*'
          Filter = "${{ inputs.filter }}"
          Recurse = [bool]"${{ inputs.recurse }}"
          Depth = [int]"${{ inputs.depth }}"
          FollowSymlinks = [bool]"${{ inputs.follow-symlinks }}"
          PassThru = $true
        }

        $scriptPath = (Join-Path "${{ github.action_path }}" "scripts" "replace-tokens.ps1")
        $result = (& $scriptPath @params)
        Write-Output -InputObject $result
