# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    name: Semantic PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Review dependencies
        uses: actions/dependency-review-action@main
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: on-failure
