# Ref: https://github.com/falnyr/replace-env-vars-action/blob/master/.github/workflows/release.yml
name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semantic-release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: setup node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: install global npm packages
        run: |
          npm install -g semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/release-notes-generator

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
