# Ref: https://github.com/falnyr/replace-env-vars-action/blob/master/.github/workflows/release.yml
name: release

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  semantic-release:
    name: create release
    runs-on: ubuntu-latest

    # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      # id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: setup node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: install global npm packages
        run: |
          npm install -g semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/release-notes-generator

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
