name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: Configure test (simple)
        id: simple
        shell: pwsh
        run: |
          $prestine = (Join-Path $pwd test stubs prestine template.tpl)
          $subject = (Join-Path $pwd test subject.tpl)
          $expected = (Join-Path $pwd test stubs expected template.tpl)

          Copy-Item -Path $prestine -Destination $subject

          Write-Output "subject-path=$subject" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append
          Write-Output "expected-path=$expected" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append

      - name: Show content before (simple)
        run: cat "${{ steps.simple.outputs.subject-path }}"

      - name: Show expected content (simple)
        run: cat "${{ steps.simple.outputs.expected-path }}"

      - name: Replace tokens (simple)
        uses: ./
        with:
          path: ${{ steps.simple.outputs.subject-path }}
          throw: true
        env:
          NAME222: 'jon'

      - name: Show content after (simple)
        run: cat "${{ steps.simple.outputs.subject-path }}"

      - name: Assert (simple)
        id: assert
        shell: pwsh
        run: |
          $subject = "${{ steps.simple.outputs.subject-path }}"
          $expected = "${{ steps.simple.outputs.expected-path }}"

          $contentActual = Get-Content -Path $subject -Raw
          $contentExpected = Get-Content -Path $expected -Raw

          if (-not $contentActual -eq $contentExpected) {
            Write-Host '✘ Test failed' -ForegroundColor Red
            exit 1
          } else {
            Write-Host '✓ Test passed' -ForegroundColor Green
            exit 0
          }
