name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: Configure tests
        id: test-config
        shell: pwsh
        run: |
          $prestineTemplate = (Join-Path $pwd test stubs prestine template.tpl)
          $testSubject = (Join-Path $pwd test subject.tpl)
          Copy-Item -Path $prestineTemplate -Destination $testSubject

          Write-Output "path=$testSubject" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append

      - name: Show content before replaced
        run: cat "${{ steps.test-config.outputs.path }}"

      - name: Replace tokens
        uses: ./
        with:
          path: ${{ steps.test-config.outputs.path }}
        env:
          name: 'jon'

      - name: Assert
        id: assert
        shell: pwsh
        run: |
          $testSubject = (Join-Path $pwd test subject.tpl)
          $expected = (Join-Path $pwd test stubs expected template.tpl)

          $actualContent = Get-Content -Path $testSubject -Raw
          $expectedContent = Get-Content -Path $expected -Raw

          if (-not $actualContent -eq $expectedContent) {
            Write-Host '✘ Test failed' -ForegroundColor Red
            exit 1
          } else {
            Write-Host '✓ Test passed' -ForegroundColor Green
            exit 0
          }

      - name: Show replaced content
        run: cat "${{ steps.test-config.outputs.path }}"
