name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.style }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        style: [envsubst, handlebars]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository for ${{ matrix.style }} test on ${{ matrix.os }}
        uses: actions/checkout@main

      - name: Setup ${{ matrix.style }} test on ${{ matrix.os }}
        id: test-setup
        shell: pwsh
        run: |
          $expected = (Join-Path $pwd test stubs expected replaced.tpl)
          $subject = (Join-Path $pwd test subject-${{ matrix.style }}.tpl)
          $prestine = (Join-Path $pwd test stubs prestine ${{ matrix.style }}.tpl)
          $untouched = (Join-Path $pwd test stubs untouched no-matches.tpl)

          $untouchedHash = (Get-FileHash -Path $untouched -Algorithm SHA256).Hash

          Copy-Item -Path $prestine -Destination $subject

          Write-Output "expected-path=$expected" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append
          Write-Output "subject-path=$subject" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append
          Write-Output "untouched-path=$untouched" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append
          Write-Output "untouched-hash=$untouchedHash" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append

      - name: Show ${{ matrix.style }} test subject before replacement on ${{ matrix.os }}
        run: cat "${{ steps.test-setup.outputs.subject-path }}"

      - name: Show expected output for ${{ matrix.style }} test on ${{ matrix.os }}
        run: cat "${{ steps.test-setup.outputs.expected-path }}"

      - name: Show untouched ${{ matrix.style }} test subject before replacement on ${{ matrix.os }}
        run: cat "${{ steps.test-setup.outputs.untouched-path }}"

      - name: Show expected hash for untouched ${{ matrix.style }} test on ${{ matrix.os }}
        run: echo "${{ steps.test-setup.outputs.untouched-hash }}"

      - name: Perform ${{ matrix.style }} test on ${{ matrix.os }}
        uses: ./
        with:
          paths: |
            ${{ steps.test-setup.outputs.subject-path }}
            ${{ steps.test-setup.outputs.untouched-path }}
          style: ${{ matrix.style }}
          throw: true
          no-newline: true
        env:
          NAME: jon

      - name: Show actual result for ${{ matrix.style }} test on ${{ matrix.os }}
        run: cat "${{ steps.test-setup.outputs.subject-path }}"

      - name: Assert ${{ matrix.style }} replacement test on ${{ matrix.os }}
        id: assert-replacement
        shell: pwsh
        run: |
          $expected = "${{ steps.test-setup.outputs.expected-path }}"
          $subject = "${{ steps.test-setup.outputs.subject-path }}"

          $expectedContent = Get-Content -Path $expected -Raw
          $actualContent = Get-Content -Path $subject -Raw

          if ($expectedContent -ne $actualContent) {
            Write-Error '✘ Replacement test failed'
            exit 1
          } else {
            Write-Host '✓ Replacement test passed'
          }

      - name: Show actual result of untouched ${{ matrix.style }} test on ${{ matrix.os }}
        run: cat "${{ steps.test-setup.outputs.untouched-path }}"

      - name: Assert ${{ matrix.style }} untouched test on ${{ matrix.os }}
        id: assert-untouched
        shell: pwsh
        run: |
          $expected = "${{ steps.test-setup.outputs.untouched-hash }}"
          $actual = (Get-FileHash -Path "${{ steps.test-setup.outputs.untouched-path }}" -Algorithm SHA256).Hash

          if ($expected -ne $actual) {
            Write-Error '✘ Untouched test failed'
            exit 1
          } else {
            Write-Host '✓ Untouched test passed'
          }
